### PR TITLE
RAF it Bro

### PR DESCRIPTION
**Pull request by longoria**
@joerozek @jasonrose 

Found this while browsing the fabricjs issue tracker:
https://github.com/kangax/fabric.js/issues/1979#issuecomment-75522942

Using `requestAnimationFrame` actually cuts grid page render time almost in half.

Here are some numbers, in seconds: (Command+A start, complete render stop)

```
Safari before:
8.00
9.00
8.36

Safari after:
4.55
4.46
4.45

Chrome before:
10.25
10.31
10.08

Chrome after:
5.86
5.96
5.83
```

### CODE REVIEW

**Comment by joerozek** [comment]
See Ben this is why you get all the performance issues.  Because you're to dang good at them. Nice work Ben!

:hamburger: :hamburger: :hamburger: :microphone: :microphone:

**Comment by gantaa** [comment]
I like how i'm still on this thread

**Comment by joerozek** [comment]
LOL

**Comment by longoria** [comment]
@gantaa ping pong?

**Pull request merged**
